require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - service_actor-rails.gemspec

Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/**/*
    - service_actor-rails.gemspec

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Gemspec/OrderedDependencies:
  Enabled: false

Bundler/GemComment:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false
